"""empty message

Revision ID: 18765d8102c6
Revises: e16c07bc96c4
Create Date: 2023-10-31 19:20:52.264010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18765d8102c6'
down_revision = 'e16c07bc96c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=400), nullable=False))
        batch_op.drop_column('task_title')
        batch_op.drop_column('task_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_content', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('task_title', sa.VARCHAR(length=40), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
