"""empty message

Revision ID: 236a83b09a5e
Revises: 4e518371bc3c
Create Date: 2023-12-05 21:27:32.155511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236a83b09a5e'
down_revision = '4e518371bc3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
