"""Add task_title column and Rename content column to task_content column

Revision ID: e16c07bc96c4
Revises: b744c517539f
Create Date: 2023-10-31 18:34:54.370262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16c07bc96c4'
down_revision = 'b744c517539f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_title', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('task_content', sa.String(length=200), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('task_content')
        batch_op.drop_column('task_title')

    # ### end Alembic commands ###
